name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['22.x', '24.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Lint
        if: matrix.node-version == '24.x'
        run: npm run lint
      - name: Types
        if: matrix.node-version == '24.x'
        run: npm run typecheck
      - name: Prettier
        if: matrix.node-version == '24.x'
        run: npm run format:check
      - name: Test
        run: npm test
